###################################################################################################

- name: import | family

  when: os_family_is_debian
     or os_family_is_redhat

  include_vars: '{{ os_family_lower }}{{ yaml_file_extension }}'

  tags:
    - artemis
    - platform
    - ssh
    - common

###################################################################################################

- name: import | overrides

  when: overrides_verified

  include_vars: '{{ overrides_path }}'

  tags:
    - artemis
    - platform
    - ssh
    - common

###################################################################################################

- name: verify

  assert:
    that:

      - ssh_user is defined
      - ssh_user is not none
      - ssh_user | length > 0

  tags:
    - artemis
    - platform
    - ssh
    - common

###################################################################################################

- name: family

  when: os_family_is_debian
     or os_family_is_redhat

  include: '{{ os_family_lower }}{{ yaml_file_extension }}'
  static : false

  tags:
    - artemis
    - platform
    - ssh
    - common

###################################################################################################

- name: discover | home

  become: true

  shell: echo ~{{ ssh_user }}

  changed_when: false

  register: home

  tags:
    - artemis
    - platform
    - ssh
    - common

###################################################################################################

- name: base

  become     : true
  become_user: '{{ ssh_user }}'

  file: dest={{ ssh_base }}
        mode={{ ssh_mode }}
       state=directory

  tags:
    - artemis
    - platform
    - ssh
    - common

###################################################################################################
