###################################################################################################

- name: debian | upgrade

  when: patch_upgrade

  become: true

  apt : upgrade={{ patch_apt_upgrade }}
        update_cache=yes

  register: upgrade

  tags:
    - artemis
    - platform
    - package
    - patch
    - debian

###################################################################################################

- name: debian | autoremove

  when: patch_autoremove
    and upgrade.changed

  become: true

  shell: DEBIAN_FRONTEND=noninteractive apt-get autoremove --yes

  tags:
    - artemis
    - platform
    - package
    - patch
    - debian

###################################################################################################

- name: debian | clean

  when: patch_clean
    and upgrade.changed

  become: true

  command: apt-get clean

  tags:
    - artemis
    - platform
    - package
    - patch
    - debian

###################################################################################################

- name: debian | signals

  when: upgrade.changed

  set_fact:
    bounce : true
    patched: true

  tags:
    - artemis
    - platform
    - package
    - patch
    - debian

###################################################################################################
